import Foundation

/// Pasteboard markers defined by [nspasteboard.org](https://nspasteboard.org) so clipboard
/// tools can skip secrets and ephemeral content.
public enum PasteboardPrivacy {
    public static let concealedType = "org.nspasteboard.ConcealedType"
    public static let transientType = "org.nspasteboard.TransientType"
    public static let autoGeneratedType = "org.nspasteboard.AutoGeneratedType"

    private static let refusedTypes: Set<String> = [
        concealedType,
        transientType,
        autoGeneratedType,
    ]

    /// Returns `true` when any type identifier signals that content must not be recorded.
    public static func shouldRefuseCapture(typeIdentifiers: some Sequence<String>) -> Bool {
        typeIdentifiers.contains { refusedTypes.contains($0) }
    }
}

/// Built-in bundle IDs that Zinc never captures from (password managers and related vaults).
public enum CaptureExclusions {
    public static let passwordManagerBundleIDs: Set<String> = [
        // 1Password
        "com.1password.1password",
        "com.1password.1password-launcher",
        "com.1password.safari",
        "com.agilebits.onepassword7",
        "com.agilebits.onepassword4",
        // Bitwarden
        "com.bitwarden.desktop",
        // LastPass
        "com.lastpass.LastPass",
        // Dashlane
        "com.dashlane.dashlanephonefinal",
        "com.dashlane.macos",
        // Apple
        "com.apple.keychainaccess",
        "com.apple.Passwords",
        // KeePass / KeePassXC
        "org.keepassx.keepassxc",
        "org.keepassxc.keepassxc",
        // Others
        "com.nordpass.macos.NordPass",
        "com.nordpass.desktop",
        "com.enpass.desktop",
        "com.keepersecurity.passwordmanager",
        "me.proton.pass.electron",
        "com.SiberSystems.RoboForm",
    ]

    public static var defaultExcludedBundleIDs: [String] {
        passwordManagerBundleIDs.sorted()
    }

    public static func isPasswordManager(bundleID: String?) -> Bool {
        guard let bundleID, !bundleID.isEmpty else { return false }
        return passwordManagerBundleIDs.contains(bundleID)
    }

    /// Save-time / trigger-time check: built-in password managers are always refused,
    /// even if the user removed them from the editable exclusion list.
    public static func shouldRefuseCapture(bundleID: String?) -> Bool {
        isPasswordManager(bundleID: bundleID)
    }
}
