import XCTest
@testable import ZincCore

final class PasteboardPrivacyTests: XCTestCase {
    func testConcealedTypeRefusesCapture() {
        XCTAssertTrue(
            PasteboardPrivacy.shouldRefuseCapture(
                typeIdentifiers: ["public.utf8-plain-text", PasteboardPrivacy.concealedType]
            )
        )
    }

    func testTransientTypeRefusesCapture() {
        XCTAssertTrue(
            PasteboardPrivacy.shouldRefuseCapture(
                typeIdentifiers: [PasteboardPrivacy.transientType, "public.html"]
            )
        )
    }

    func testAutoGeneratedTypeRefusesCapture() {
        XCTAssertTrue(
            PasteboardPrivacy.shouldRefuseCapture(
                typeIdentifiers: [PasteboardPrivacy.autoGeneratedType]
            )
        )
    }

    func testOrdinaryTypesAllowCapture() {
        XCTAssertFalse(
            PasteboardPrivacy.shouldRefuseCapture(
                typeIdentifiers: [
                    "public.utf8-plain-text",
                    "public.html",
                    "public.png",
                ]
            )
        )
    }

    func testEmptyTypesAllowCapture() {
        XCTAssertFalse(PasteboardPrivacy.shouldRefuseCapture(typeIdentifiers: [String]()))
    }

    func testPasswordManagerBundleIDsAreExcluded() {
        XCTAssertTrue(CaptureExclusions.shouldRefuseCapture(bundleID: "com.1password.1password"))
        XCTAssertTrue(CaptureExclusions.shouldRefuseCapture(bundleID: "com.bitwarden.desktop"))
        XCTAssertTrue(CaptureExclusions.shouldRefuseCapture(bundleID: "com.apple.keychainaccess"))
        XCTAssertTrue(CaptureExclusions.shouldRefuseCapture(bundleID: "com.apple.Passwords"))
        XCTAssertFalse(CaptureExclusions.shouldRefuseCapture(bundleID: "com.apple.Safari"))
        XCTAssertFalse(CaptureExclusions.shouldRefuseCapture(bundleID: nil))
        XCTAssertFalse(CaptureExclusions.shouldRefuseCapture(bundleID: ""))
    }

    func testDefaultExcludedListIncludesPasswordManagers() {
        let defaults = Set(CaptureExclusions.defaultExcludedBundleIDs)
        XCTAssertEqual(defaults, CaptureExclusions.passwordManagerBundleIDs)
        XCTAssertTrue(defaults.contains("com.1password.1password"))
        XCTAssertTrue(defaults.contains("com.bitwarden.desktop"))
    }
}
